// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// InfoMetaTags defines meta tags for the info page.
func InfoMetaTags() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<meta name=\"keywords\" content=\"gowebly, htmx, templ, go, web framework\"><meta name=\"description\" content=\"Information about this Gowebly project and its technologies.\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// InfoBodyContent defines the HTML content for the info page.
func InfoBodyContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"app\"><div><a href=\"https://gowebly.org\" target=\"_blank\"><img src=\"/static/images/gowebly.svg\" class=\"gowebly logo\" alt=\"Gowebly logo\"></a><h1>Project Information</h1><div class=\"content\"><div class=\"info-section\"><h2 class=\"text-2xl font-bold mb-4\">Technology Stack</h2><ul class=\"list-disc list-inside text-left max-w-md mx-auto\"><li><strong>Backend:</strong> Go with Templ and htmx</li><li><strong>Frontend:</strong> Tailwind CSS with DaisyUI</li><li><strong>Build Tool:</strong> Parcel</li><li><strong>Templating:</strong> Go Templ</li></ul></div><div class=\"info-section mt-8\"><h2 class=\"text-2xl font-bold mb-4\">Key Features</h2><ul class=\"list-disc list-inside text-left max-w-md mx-auto\"><li>Server-side rendering with Go Templ</li><li>HTMX for dynamic interactions</li><li>Responsive design with Tailwind CSS</li><li>Component-based architecture</li><li>Optimized asset building with Parcel</li></ul></div><div class=\"info-section mt-8\"><h2 class=\"text-2xl font-bold mb-4\">Project Structure</h2><ul class=\"list-disc list-inside text-left max-w-md mx-auto\"><li><code>main.go</code> - Application entry point</li><li><code>server.go</code> - HTTP server configuration</li><li><code>handlers.go</code> - HTTP handlers</li><li><code>templates/</code> - Templ components</li><li><code>assets/</code> - Source CSS/JS files</li><li><code>static/</code> - Built assets</li></ul></div><div class=\"mt-8\"><a href=\"/\" class=\"button-link\">← Back to Home</a></div></div><p class=\"read-the-docs\"><a href=\"https://gowebly.org\" target=\"_blank\">Documentation</a> ⋅ <a href=\"https://github.com/gowebly/gowebly\" target=\"_blank\">GitHub</a></p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
